### ISSUE TITLE
Can't connect to Mongodb 5.x

### ISSUE THREAD

**Issue by adityapatadia** [newrelic/nri-mongodb#76] opened 2021-12-22 12:37 UTC
I get following error in logs
`Failed to create session: server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field."`

I think the problem is with old drivers.

**Comment by literakl** [comment] 2021-12-25 12:36
The mongo agent stopped working on my nodes since I upgraded Mongo from 4.4 to 5.0:

Dec 25 13:15:21 db1 newrelic-infra-service[744]: time="2021-12-25T13:15:21+01:00" level=warning msg="integration exited with error state" component=integrations.runner.Runner error="exit status 1" integration_name=nri-mongodb stderr="[WARN] Using the deprecated config ClusterName instead of MongodbClusterName\n[ERR] Failed to create session: server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field."

**Comment by alvarocabanas** [comment] 2022-01-14 16:06
Hello, thanks for raising this issue, it has been accepted and it is going to be prioritized.

**Comment by Achar007** [comment] 2022-01-26 14:10
When we can expect a fix for this bug ?

**Comment by gsanchezgavier** [comment] 2022-02-04 10:41
I have [reproduced](https://github.com/newrelic/nri-mongodb/runs/5065078142?check_suite_focus=true#step:5:113) this issue and I think is also related to the old driver. This should be resolved when #71 is addressed. 

Did a quick check using the branch mentioned in #67 but that did not resolve the issue.

**Comment by noahjd** [comment] 2022-02-10 00:30
Having a similar issue, when can we expect a fix for this?

**Comment by Dgadavin** [comment] 2022-04-26 08:24
Can you please provide the info on when this can be fixed? Thanks a lot. We really need this integration works on Mongo 5.x

**Comment by yndo97** [comment] 2022-04-26 09:50
The same issue. Could you please provide any ETA?

**Comment by acharbha** [comment] 2022-05-18 07:35
is there a mongodb patch available to fix this ?

**Comment by mangulonr** [comment] 2022-05-26 07:42
Hi 

We plan to work on update MongoDB OHI to support v5 during FY23Q2.

**Comment by pyrotechnics-io** [comment] 2022-06-28 03:46
Would v5 support also include this feature (which has been supported on MongoDB since 4.0) ?
 https://github.com/globalsign/mgo/pull/282

**Comment by pyrotechnics-io** [comment] 2022-09-18 04:40
> Any chance to get it soon ?

There is a [fork that's under testing](https://github.com/pyrotechnics-io/nri-mongodb/tree/hbaste-scramsha256). If you're game to try it out, any bug reports are more than welcome.

**Comment by mangulonr** [comment] 2023-02-20 15:02
Hi

The [new MongoDB OHI](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/) has been released in public preview, this version will be GA during June.

**Some of the new features provided:**

- Compatibility with [MongoDB Atlas](https://www.mongodb.com/cloud/atlas/efficiency).
- Support of the latest major MongoDB versions 5 and 6.
- Compatibility with [Percona Server for MongoDB](https://www.percona.com/software/mongodb/percona-server-for-mongodb).
- Support of SCRAM authentication.
- Integration with the [entity explorer](https://one.newrelic.com/nr1-core) thanks to 3 new entity types (MongoDB instance, database, and collection).
- Improved new [MongoDB quickstart](https://newrelic.com/instant-observability/mongodb-prometheus).
- Improved [metrics filtering capabilities](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/#instance-settings).

For more information check the following resources.

- [Documentation](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/)
- [Migration guide](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-migration-guide/)
- [Quickstart](https://newrelic.com/instant-observability/mongodb-prometheus)

Because it is based on Prometheus the metric names are different from our [legacy](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration/) OHI, check our [migration guide](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-migration-guide/) if you need more details.
Our [legacy](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration/) MongoDB OHI will be deprecated on FY24H2 (final date pending to be decided).

**Closed** 2023-02-22 09:46 UTC
Labels: bug, triage/accepted
